### ISSUE TITLE
Add ROI to test data

### ISSUE THREAD

**Issue by CFGrote** [German-BioImaging/omero-ontop-mappings#7]
To test queries for ROIs we need ROIs to be present on some test images. 

- [ ] omero cli or omero-py script that adds 2 ROIs to Image/5 and Image/6
- [ ] confirm test_image_roi passes.

**Comment by joshmoore** [comment]
:+1: 

To the use of the CLI:

> `omero obj new Roi name=foo description=bar image=Image:1 shapes=Rectangle`
> I get AttributeError: 'RoiI' object has no attribute 'getSetShapes' or 'isSetShapes'

Not a huge surprise. This is likely something that's fixable, but will require new syntax like: shapes=Rectangle:1,Polygon:2

**Comment by CFGrote** [comment]
Need to fix tests that count number of images: 10->12
